
baseURL = "https://wordkpop.com/"
languageCode = "en-us"
title = "Word Kpop"
theme = "ananke"

enableRobotsTXT = true
buildFuture = false

[pagination]
pagerSize = 10

[params]
  mainSections = ["posts"]
